# Generated by Django 4.1.7 on 2023-03-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Isbn',
            new_name='isbn',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Subtitle',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Title',
            new_name='title',
        ),
    ]
